# name字段是 workflow 的名称。如果省略该字段，默认为当前 workflow 的文件名
name: Electron Builder Action

# on字段指定触发 workflow 的条件，通常是某些事件。这里设置打 tag 标签且标签名称为v.*.*.*时触发
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    # 在什么平台上运行，取值为下面 strategy 设置的 matrix.os 的数组参数，在mac 和 windows 下运行（即打包 mac 和 windows 平台）
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: 检出代码到本地
        uses: actions/checkout@v2

      - name: 安装 Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: 构建
        run: |
          yarn
          yarn electron:build
      
      # win 系统免安装的包 命令默认使用非登录 shell 运行
      - name: 压缩 win 系统可直接运行的包
        if: ${{ runner.os == 'Windows' }}
        run: zip -r ./dist_electron/win-64-unpacked.zip ./dist_electron/win-unpacked

      - name: 发布到 github 的 releases
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "dist_electron/*.dmg,dist_electron/*.exe,dist_electron/win-64-unpacked.zip"
